In [1]:
import pandas as pd
import ta
from binance import Client
import numpy as np

In [2]:
client = Client()

In [3]:
def getdata(symbol):
    frame = pd.DataFrame(client.get_historical_klines(symbol,
                                                     '15m',
                                                     '1000 hours ago UTC'))
    frame = frame.iloc[:,0:6]
    frame.columns = ['Time','Open','High','Low','Close','Volume']
    frame.set_index('Time',inplace=True)
    frame.index = pd.to_datetime(frame.index, unit='ms')
    frame = frame.astype(float)
    return frame

In [4]:
df = getdata('ETHUSDT')

In [5]:
df

Open     High      Low    Close     Volume
Time                                                              
2022-03-15 09:00:00  2516.63  2520.31  2510.37  2520.11  3479.1802
2022-03-15 09:15:00  2520.12  2535.77  2520.11  2529.52  3894.2497
2022-03-15 09:30:00  2529.52  2534.70  2525.30  2532.45  1841.1285
2022-03-15 09:45:00  2532.44  2534.96  2527.25  2529.63  1420.6660
2022-03-15 10:00:00  2529.63  2537.22  2527.73  2534.53  1974.3831
...                      ...      ...      ...      ...        ...
2022-04-25 23:45:00  3010.45  3013.09  3003.17  3006.62  3656.1121
2022-04-26 00:00:00  3006.63  3016.99  3005.63  3011.19  5822.9953
2022-04-26 00:15:00  3011.19  3019.56  3006.80  3018.00  4682.3703
2022-04-26 00:30:00  3018.01  3039.54  3014.00  3020.91  6529.6601
2022-04-26 00:45:00  3020.92  3023.89  3013.16  3013.21  2158.7548

[4000 rows x 5 columns]

In [6]:
def applytechnicals(df):
    for i in range(2,10,2):
        df['rsi_'+str(i)] = ta.momentum.rsi(df.Close, window=i)
        df['SMA_'+str(i*10)] = df.Close.rolling(i*10).mean()
    df['macd'] = ta.trend.macd_diff(df.Close)
    df.dropna(inplace=True)

In [7]:
applytechnicals(df)

In [8]:
df

Open     High      Low    Close     Volume      rsi_2  \
Time                                                                            
2022-03-16 04:45:00  2616.29  2623.90  2616.28  2618.92  1673.6290  48.607285   
2022-03-16 05:00:00  2618.92  2623.19  2613.49  2622.56  2398.8614  74.952976   
2022-03-16 05:15:00  2622.55  2624.45  2611.96  2617.40  2759.5541  30.550605   
2022-03-16 05:30:00  2617.39  2632.92  2613.88  2628.50  3873.7127  80.429683   
2022-03-16 05:45:00  2628.50  2631.81  2624.25  2628.30  1576.8734  78.400570   
...                      ...      ...      ...      ...        ...        ...   
2022-04-25 23:45:00  3010.45  3013.09  3003.17  3006.62  3656.1121  13.794436   
2022-04-26 00:00:00  3006.63  3016.99  3005.63  3011.19  5822.9953  65.460441   
2022-04-26 00:15:00  3011.19  3019.56  3006.80  3018.00  4682.3703  87.603353   
2022-04-26 00:30:00  3018.01  3039.54  3014.00  3020.91  6529.6601  91.991264   
2022-04-26 00:45:00  3020.92  3023.89  3013.16  3013.21  2158.7548  32.017144   

                        SMA_20      rsi_4      SMA_40      rsi_6       SMA_60  \
Time                                                                            
2022-03-16 04:45:00  2638.9985  34.455900  2635.17775  37.929917  2617.925500   
2022-03-16 05:00:00  2638.9815  43.194713  2634.52275  41.980204  2619.314333   
2022-03-16 05:15:00  2639.0080  34.500484  2633.68550  37.785875  2620.361500   
2022-03-16 05:30:00  2639.7185  58.474030  2633.04800  50.541773  2621.480000   
2022-03-16 05:45:00  2640.5765  57.964346  2632.26950  50.318703  2622.656833   
...                        ...        ...         ...        ...          ...   
2022-04-25 23:45:00  3003.7135  36.987097  2955.01800  50.928003  2917.327667   
2022-04-26 00:00:00  3006.4215  58.528486  2958.91575  61.077612  2920.714333   
2022-04-26 00:15:00  3007.9795  75.303187  2962.64425  71.586424  2924.178833   
2022-04-26 00:30:00  3008.4885  79.928744  2966.15825  75.041795  2927.350833   
2022-04-26 00:45:00  3008.5285  48.127112  2969.70850  54.137139  2930.450167   

                         rsi_8       SMA_80      macd  
Time                                                   
2022-03-16 04:45:00  40.760218  2597.193625 -6.105040  
2022-03-16 05:00:00  43.335204  2598.474250 -5.466375  
2022-03-16 05:15:00  40.484265  2599.572750 -5.146156  
2022-03-16 05:30:00  48.770093  2600.773375 -3.992913  
2022-03-16 05:45:00  48.630676  2602.006750 -3.090043  
...                        ...          ...       ...  
2022-04-25 23:45:00  58.654142  2897.334125 -4.173234  
2022-04-26 00:00:00  64.296486  2899.119750 -4.210673  
2022-04-26 00:15:00  71.029460  2901.024125 -3.799371  
2022-04-26 00:30:00  73.472498  2902.955875 -3.368597  
2022-04-26 00:45:00  58.543190  2904.808625 -3.617629  

[3921 rows x 14 columns]

In [ ]:
# df.Close

In [ ]:
# df.Close.shift(-1) - df.Close

In [9]:
def x_y(df, period):
    y = df.Close.shift(-period) - df.Close
    y = y[:-period]
    x = df[:-period]
    y = np.where(y>0,1,0)
    return x,y

In [10]:
x,y = x_y(df,1)

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [12]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,
                                                    random_state=1,
                                                    shuffle=False)

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
clf = RandomForestClassifier(random_state=1)

In [20]:
clf.fit(x_train, y_train)

RandomForestClassifier(random_state=1)

In [21]:
pred = clf.predict(x_test)

In [22]:
pred

array([1, 1, 0, ..., 1, 1, 1])

In [27]:
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix

In [24]:
confusion_matrix(y_test, pred)

array([[293, 304],
       [245, 334]], dtype=int64)

In [25]:
tn, fp, fn, tp = confusion_matrix(y_test, pred).ravel()

In [26]:
tn

293

In [28]:
accuracy_score(y_test, pred)

0.5331632653061225

In [29]:
precision_score(y_test, pred)

0.5235109717868338